### ISSUE TITLE
Unable to install 'kubescape.kubescape' extension because it is not compatible with the current version of VS Code (version 1.39.2)

### ISSUE THREAD

**Issue by reply-mj** [armosec/vscode-kubescape#1]
Unable to install 'kubescape.kubescape' extension because it is not compatible with the current version of VS Code (version 1.39.2)

**Comment by xdavidel** [comment]
Hi,

Basically we're only supporting VSCode 1.50 and above (A version from two years ago)
I **highly** recommend that you update your VSCode to a more recent version, regardless of your plans for _Kubescape_, since 
_nodejs_ packages (and by extent _Electron_ based apps) are known to have a lot of vulnerabilities.

Is there a reason for you to keep this old version ~(1.39.2)~ around?
